name: Build test deploy secret

on:
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install, Build, Test
      run: |
        npm ci
        npm run build --if-present
        npm test

  stage_deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      - name: Deploy To Staging
        run: |
          echo "Deployed to staging environment"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2

  production_deploy:
    runs-on: ubuntu-latest
    needs: stage_deploy
    environment:
      name: production

    steps:
      - name: Deploy To Production
        run: |
          echo "Deployed to production environment"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2